apiVersion: apps/v1
kind: Deployment
metadata:
  name: hello-deployment
  namespace: apps
  labels:
    app: hello
spec:
  replicas: 3
  selector:
    matchLabels:
      app: hello
  template:
    metadata:
      labels:
        app: hello
    spec:
      containers:
        - name: hello
          image: rost2001/hello-spring_app
          imagePullPolicy: IfNotPresent